In [2]:
import pandas as pd
from os import listdir
from os.path import isfile, join
from functools import reduce

In [3]:
path = 'Magistro duomenys/combined/odf'

In [4]:
data_files = [f for f in listdir(path) if isfile(join(path, f))]

In [5]:
dfs = []
for file in data_files:
    df = pd.read_excel('{}/{}'.format(path, file))
    df = df.rename(columns={'Unnamed: 0': "time"})
    
    dfs.append(df)

In [ ]:
res_df = pd.DataFrame(columns = ['time'])

In [6]:
for df in dfs:
    res_df = res_df.merge(df, left_on='time', right_on='time', how='outer')

In [7]:
res_df = reduce(lambda left,right: pd.merge(left,right,on='time'), dfs)

In [8]:
res_df.sort_values(by=['time'])

,time,Prognozuojama vėjo elektrinių gamyba,Vėjo elektrinių gamybos planas,Faktinė vėjo elektrinių gamyba,Planuojama nacionalinė elektros energijos gamyba,Faktinė nacionalinė elektros energijos gamyba,Prognozuojamas nacionalinis elektros energijos suvartojimas,Planuojamas nacionalinis elektros energijos suvartojimas,Faktinis nacionalinis Elektros energijos vartojimas,Nord Pool Lietuva
0,2013-01-01 00:00:00,NaN,0.0,196.000,323.0,534.000,990.0,1010.00,951.000,38.00
1,2013-01-01 01:00:00,NaN,0.0,200.000,340.0,551.000,935.0,945.00,904.000,24.00
2,2013-01-01 02:00:00,NaN,0.0,193.000,360.0,563.000,880.0,880.00,857.000,24.00
3,2013-01-01 03:00:00,NaN,0.0,177.000,360.0,548.000,845.0,845.00,814.000,24.00
4,2013-01-01 04:00:00,NaN,0.0,159.000,360.0,531.000,820.0,824.00,790.000,24.00
...,...,...,...,...,...,...,...,...,...,...
69998,2021-01-01 19:00:00,10.0,10.0,-0.997,398.8,373.816,1371.0,1369.17,1407.704,53.01
69999,2021-01-01 20:00:00,11.0,11.0,-1.000,401.2,402.184,1340.0,1330.97,1372.420,55.74
70000,2021-01-01 21:00:00,13.0,13.0,-1.466,390.0,369.630,1282.0,1285.97,1331.050,54.94
70001,2021-01-01 22:00:00,14.0,14.0,-1.507,237.3,218.937,1199.0,1194.17,1257.264,50.82
70002,2021-01-01 23:00:00,15.0,15.0,-1.500,221.6,200.928,1117.0,1117.57,1193.192,45.22

In [10]:
res_df.to_csv('Magistro duomenys/processed/model_data.csv')